[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
async_fsm = { path = "../async_fsm" }
tokio = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
