[workspace]
members = ["async_fsm", "example"]
resolver = "2"

[workspace.dependencies]
log = "0.4.25"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
] }
async-trait = "0.1.86"
env_logger = "^0.9"
