[package]
name = "generated_fsm"
version = "0.1.0"
edition = "2021"

[dependencies]
async_fsm = { version = "0.1.3" }
log = "0.4.25"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
] }
async-trait = "0.1.86"
env_logger = "^0.9"
